language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source --dev

script:
  - make test
  - vendor/bin/phpunit --coverage-clover=coverage.xml

matrix:
  include: 
    - php: hhvm
      dist: trusty
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
